#!/usr/bin/env bash
# configures a brand new Ubuntu machine
apt-get update
apt-get install -y nginx

HOSTNAME=$(cat /etc/hostname)
CONFIGURED=$(grep -c "add_header X-Served-By \"$HOSTNAME\"" /etc/nginx/sites-enabled/default)

if [ "$CONFIGURED" = 0 ]; then
    sed -i "/listen \[::\]:80 default_server;/a \\\n\tadd_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-enabled/default
fi

service nginx restart
