#!/usr/bin/env bash
# Install and configure a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 45214-web-01 3.237.19.192:80 check\n\tserver 45214-web-02 54.236.8.116:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
